version: 2.1

orbs:
  architect: giantswarm/architect@0.14.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: confetti-backend
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-confetti-backend-to-quay
          context: architect
          image: "quay.io/giantswarm/confetti-backend"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: "package and push"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "confetti-backend"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - push-confetti-backend-to-quay
