version: 2.1

orbs:
  architect: giantswarm/architect@0.14.0

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: confetti-backend
          filters:
            tags:
              only: /^v.*/
