name: confetti-backend
namespace: giantswarm
userID: 1000
groupID: 1000
image:
  repository: giantswarm/confetti-backend
  tag: 0.0.0-441017f289c826ab3711579937d4187e4563f9bb
ports:
  confetti-backend-service:
    port: 8000
    protocol: TCP
